from src.api.metadata.title import title
from src.api.metadata.summary import summary
from src.api.metadata.description import description
from src.api.metadata.version import version
from src.api.metadata.openapi_url import openapi_url
from src.api.metadata.terms_of_service import terms_of_service
from src.api.metadata.contact import contact
from src.api.metadata.license_info import license_info
from src.api.metadata.tags_metadata import tags_metadata
from src.api.metadata.swagger_ui_parameters import swagger_ui_parameters
