"""update-telegram-user-foreign-key

Revision ID: 009103c7876b
Revises: fcc8e8b0672f
Create Date: 2025-07-26 01:41:11.253698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009103c7876b'
down_revision: Union[str, Sequence[str], None] = 'fcc8e8b0672f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('telegram_users_ibfk_1'), 'telegram_users', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_users', 'users', ['userId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.create_foreign_key(op.f('telegram_users_ibfk_1'), 'telegram_users', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
