"""User-password

Revision ID: 0aa9aba2c9bf
Revises: 009103c7876b
Create Date: 2025-08-02 01:46:15.966208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa9aba2c9bf'
down_revision: Union[str, Sequence[str], None] = '009103c7876b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###
