"""crypto-currency-composit-keys

Revision ID: 34a6275f9726
Revises: da20c207a973
Create Date: 2025-07-20 15:57:50.202266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a6275f9726'
down_revision: Union[str, Sequence[str], None] = 'da20c207a973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'crypto', ['symbol'])
    op.create_unique_constraint(None, 'currencies', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currencies', type_='unique')
    op.drop_constraint(None, 'crypto', type_='unique')
    # ### end Alembic commands ###
