"""update-foreign-keys

Revision ID: fcc8e8b0672f
Revises: 34a6275f9726
Create Date: 2025-07-25 01:52:32.025888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc8e8b0672f'
down_revision: Union[str, Sequence[str], None] = '34a6275f9726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('crypto_subscribes_ibfk_1'), 'crypto_subscribes', type_='foreignkey')
    op.drop_constraint(op.f('crypto_subscribes_ibfk_2'), 'crypto_subscribes', type_='foreignkey')
    op.create_foreign_key(None, 'crypto_subscribes', 'crypto', ['symbolId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'crypto_subscribes', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('currency_subscribes_ibfk_2'), 'currency_subscribes', type_='foreignkey')
    op.drop_constraint(op.f('currency_subscribes_ibfk_1'), 'currency_subscribes', type_='foreignkey')
    op.create_foreign_key(None, 'currency_subscribes', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'currency_subscribes', 'currencies', ['symbolId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_subscribes', type_='foreignkey')
    op.drop_constraint(None, 'currency_subscribes', type_='foreignkey')
    op.create_foreign_key(op.f('currency_subscribes_ibfk_1'), 'currency_subscribes', 'currencies', ['symbolId'], ['id'])
    op.create_foreign_key(op.f('currency_subscribes_ibfk_2'), 'currency_subscribes', 'users', ['userId'], ['id'])
    op.drop_constraint(None, 'crypto_subscribes', type_='foreignkey')
    op.drop_constraint(None, 'crypto_subscribes', type_='foreignkey')
    op.create_foreign_key(op.f('crypto_subscribes_ibfk_2'), 'crypto_subscribes', 'users', ['userId'], ['id'])
    op.create_foreign_key(op.f('crypto_subscribes_ibfk_1'), 'crypto_subscribes', 'crypto', ['symbolId'], ['id'])
    # ### end Alembic commands ###
